# Introduction {.unnumbered .unlisted}

<!--
  This is the first page of the Snap! Manual.
  The manual title is already included on the top of this page by Quarto.

  We need to include some title, but don't want it to be redundant.
-->

::: {.callout-note}
## This a work in progress!

Welcome to the "new" {.snap}`Snap` manual. However, there are still many images and pages that need proper formatting and updates for version 11.

You may wish to [read a very nicely typeset version][pdf] of the manual.

[pdf]: https://snap.berkeley.edu/snap/help/SnapManual.pdf
:::

**Version 11.0**

{.snap}`Snap` (formerly BYOB) is an extended reimplementation of Scratch
(<u>https://scratch.mit.edu</u>) that allows you to Build Your Own
Blocks. It also features ﬁrst class lists, first class procedures, first
class sprites, first class costumes, first class sounds, and first class
continuations. These added capabilities make it suitable for a serious
introduction to computer science for high school or college students.

In this manual we sometimes make reference to Scratch, e.g., to explain
how some {.snap}`Snap` feature extends something familiar in Scratch. It’s
very helpful to have some experience with Scratch before reading this
manual, but not essential.

To run {.snap}`Snap`, open a browser window and
visit [`https://snap.berkeley.edu/snap`](https://snap.berkeley.edu/snap). The {.snap}`Snap` community web site
at https://snap.berkeley.edu is covered briefly in @sec-appendix-community


The manual is roughly organized into a few sections.

* Chapters 1 to 11 cover the primary features for writing programings in
Snap*!*. They are organized from introductory to advanced topics.
* Chapters 12 and 13 cover the user interface components of both the Snap*!* editor and the community site.
* The appendicies provide [documentation for every block in {.snap}`Snap` block][blocks], as well as some of libraries provided.

[blocks]: /blocks/

<!-- TODO: Hide this from the PDF. -->
::: {.content-visible when-format="html"}
## Features of the Manual

You'll find the table of contents on the left side of each page. At the bottom of each page, you'll find previous and next links to navigate the manual in order.

A search function is included in the upper right hand corner. If you which you can type <kbd>/</kbd> (or <kbd>?</kbd>) to jump to the search function.
:::

::: {.content-visible when-format="pdf"}
## The 'New' PDF Manual {.unnumbered .unlisted}

this is currently a work in progress.
:::
