on:
  workflow_dispatch:
  push:
    branches:
      - main
      - quarto

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install jupyter
      - name: Render Book project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
      - name: Publish HTML book
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
